### ISSUE TITLE
Store.createFragment pushes records into the store but not Store.push

### ISSUE THREAD

**Issue by jakesjews** [lytics/ember-data-model-fragments#134]
Whenever store.createFragment gets called a record is pushed into the ember-data store. This doesn't happen in version 0.3.3 but I wasn't sure if this was a new behavior. Calling store.push seems to behave differently because it doesn't push any fragments into the store. 

We think this may be causing an issue when combined with the [stained-by-children mixin](https://github.com/eflexsystems/ember-cli-stained-by-children/tree/1.13) since newly saved fragments in child records are being destroyed on rollback but aren't destroyed on rollback when the data is originally loaded from the server.

[Twiddle demonstrating the issue](http://ember-twiddle.com/558aadf44e6fcf4bc297?numColumns=1)

**Comment by slindberg** [comment]
> Whenever store.createFragment gets called a record is pushed into the ember-data store. This doesn't happen in version 0.3.3 but I wasn't sure if this was a new behavior

Fragments should never be pushed into the store, so this is definitely a bug on that level :persevere:

**Comment by jakesjews** [comment]
whoops hit the wrong button sorry. Meant to say I thought the fragments appearing in the store might be a bug but wasn't sure with the 1.13 changes.

**Comment by slindberg** [comment]
I looked into this a few weeks ago, but realized I never posted my findings. In short, it would be exceedingly difficult to prevent ED from creating live records for model fragments with the `internalModel` changes. I think I'd rather address concrete side effects of this behavior, e.g. the destroy on rollback issue you mentioned. Do you think you could create a failing test that demonstrates the issue?

**Comment by jakesjews** [comment]
It's probably not an actual issue with model-fragments. We're using a modified version of the [stained-by-children addon](https://github.com/lolmaus/ember-cli-stained-by-children) to mark embedded saved records as clean and the problem we were running into was newly saved fragments in embedded objects being were being removed from the store after a rollback. 

The solution we came up with was calling adapterDidCommit on every embedded child's fragments when a parent object gets saved. We also needed to fork this repo and [tweak adapterDidCommit](https://github.com/jakesjews/ember-data.model-fragments/commit/d95fb1b0a0d1e3ab59ffd659b944f450346eeeb6) on model-fragment.js. I'm probably going to replace the fork with re-opening the class in our app.

Our use case is weird enough that I don't think its fair to expect a fix but it would be really nice to have a function to call to make fragments clean. I could put together a PR if you think it would be acceptable.

**Comment by slindberg** [comment]
Were fragments getting removed from the store on save, or were they only getting removed when rolling back the parent record? Or does stained-by-children do a rollback as part of marking the embedded records as clean? Also, I'm unsure what the negative effects of a fragment getting removed from the store actually are; do they also get changed to the deleted state?

I'm hesitant to provide official support for marking a fragment as clean. There's a number of good reasons that ED doesn't do it, and until it does (if ever), I'd like to avoid it too. I think reopening the class for your use case is the best way to go about this; forking addons is a fucking pain, especially ones like this one with dist dirs. But again, if there's an underlying issue we can address, then let's do it.

**Comment by jakesjews** [comment]
Sorry for the poor explanation of whats going on. Heres a [repository](https://bitbucket.org/eflexsystems/ember-data-embedded-bug/overview) showing what I'm talking about. The basic problem is that if you save a parent object with embedded records then rollback one of the embedded records any of the fragments inside that child are deleted even though they were persisted to the server. You can replicate it in the example app by clicking the add button, saving the parent record, the clicking rollback on the child. This probably isn't an issue you need to worry about so you can probably just close this issue. Thanks for the awesome addon!
