### ISSUE TITLE
Ember Data default serializers cannot be looked up

### ISSUE THREAD

**Issue by thec0keman** [lytics/ember-data-model-fragments#160]
Calling `store.serializerFor('application')` will fail with `No model was found for 'application'`.

I believe this is because in the [override](https://github.com/lytics/ember-data-model-fragments/blob/master/packages/model-fragments/lib/fragments/ext.js#L88) version we first call `modelFor`, which is a bit differ of a [path](https://github.com/emberjs/data/blob/master/packages/ember-data/lib/system/store.js#L1972) than in Ember Data.

**Comment by slindberg** [comment]
Thanks for reporting this :beers:, fixed in #162 release to follow soon.
