### ISSUE TITLE
Fragment still dirty after save

### ISSUE THREAD

**Issue by dwickern** [lytics/ember-data-model-fragments#164]
After upgrading to version 1.13.x I have an issue where a fragment is dirty after saving the model. I tried to write a test for this but ultimately couldn't.

The fragment in question has two `DS.attr('string')` properties which are left as their default value `null` when I fetch the model. After I call `save`, it thinks I changed `null` to `null` and thus the fragment is dirty:
```
fragment.get('isDirty')
> true
fragment.changedAttributes()
> {property1:[null,null],property2:[null,null]}
```

My PUT method echoes back the same JSON which is passed to it (including these null properties). If I leave the two properties out/undefined, the fragment will not be dirty after the save.

git bisect blames this commit: @25a46885025b31e7420da07fcc1d3ffa04853f45

**Comment by slindberg** [comment]
Cooooool, gotta love those uncaught regressions :grimacing: . I'll try to track this down this weekend.

**Comment by workmanw** [comment]
Yeap, our tests detected this failure too. I'd be happy to build a failing test for this and submit a PR if needed.

**Comment by dwickern** [comment]
After some more testing, I'm observing this behavior:

I load the model and the fragment is not dirty. Once I bind the model properties to a component, the fragment becomes dirty. `changedAttributes` thinks everything was changed from `null` to whatever the loaded value was.

So that explains why I couldn't write a unit test...

**Comment by slindberg** [comment]
@workmanw failing tests are always welcome :grin:

**Comment by coachTomato** [comment]
I had the same problem in my project. Please consider also the DS.attr() attributes.

**Comment by workmanw** [comment]
@slindberg Sorry for the delay! I opened a PR for the failing test. As @dwickern mentioned, it has something to do with the attribute, if you don't ever get the property, it seems fine.

I don't know if this is the exact issue I have because I'm pushing updates into the store in my case. But given that @25a4688 is also the culprit, they seem related.

**Comment by workmanw** [comment]
Unfortunately this is a blocker for us. Is there any way I can help out here? I tried to debug it a little bit, but it's pretty clear I need to some knowledge of ember-data internals. Any guesses, I'd be happy to explore some options.

**Comment by slindberg** [comment]
@dwickern, I fixed @workmanw's issue in #167, but I'm not entirely sure that it fixes yours. It sounds like you are able to build a version of MF and use it in your app. Would you mind building from master to see?

**Comment by dwickern** [comment]
@slindberg I tried running against master but everything broke. Any chance you could backport the fix to the 1.13.x branch?

I'm running ember 1.13.10, ember-data 1.13.15, model-fragments 0.4.3

**Comment by slindberg** [comment]
@dwickern I cherry picked the fixes onto the `release-1-13` branch, which is tracking the 1.13.x series. Once you verify, I'll release v1.13.2 and v2.1.1. Thanks for testing :+1:

**Comment by dwickern** [comment]
@slindberg looks good :+1:

**Comment by slindberg** [comment]
Sorry for the delay, finally got around to releasing v1.13.2, v2.0.2, and v2.1.1 with fixes for this issue.

**Comment by dwickern** [comment]
@slindberg thanks so much! Could you publish v1.13.2 and v2.0.2 to npm?

**Comment by slindberg** [comment]
Oh damn sorry about that, I don't know how that happened. Should be published now.
