### ISSUE TITLE
Fragment serializer and application serializer

### ISSUE THREAD

**Issue by shen6653** [lytics/ember-data-model-fragments#166]
In v0.4.1, if there is no serializer defined for the model fragment, the defined application serializer will be applied. However, after upgrading to v1.13.1, this no longer works. Is this intended or a bug?

**Comment by DingoEatingFuzz** [comment]
Intended: https://github.com/lytics/ember-data-model-fragments/issues/135

**Comment by workmanw** [comment]
In the short term, I just created the following initializer: 

```
// app/initializers/fragment-serializer.js
import ApplicationSerializer from 'app/serializers/application';


export default {
  name: 'FragmentSerializer',
  before: 'store',
  after: 'fragmentTransform',
  initialize: function(container) {
    container.register('serializer:-fragment', ApplicationSerializer);
  }
};
```

This change caught me off guard, but I definitely appreciate the fact that this is a separate serializer. My application serializer has specific logic for fragments and I'm excited to be able to easily unwind that when I have time.

**Comment by shen6653** [comment]
Thanks for the quick response!

**Comment by slindberg** [comment]
And now for the extremely delayed response...

There's a blurb buried in the [serializing section of the readme](https://github.com/lytics/ember-data-model-fragments#serializing) that explains the reasoning for not using the application serializer. @workmanw's suggestion is the correct way to deal with using a default fragment serializer, and unfortunately I think it's the long-term solution.

The `application` serializer is essentially a reserved word in the Ember API, and I cannot look for a `fragment` serializer without potential clashing with apps out there that have a model named `fragment`. Registering a serializer with the container manually is the only way for it to be resolved without the namespacing issue (hence the pre-dashed `-fragment`).
