### ISSUE TITLE
Getting ENOENT from source maps in 1.13.1

### ISSUE THREAD

**Issue by devinus** [lytics/ember-data-model-fragments#170]
```
ENOENT: no such file or directory, stat '/Users/devinus/Projects/rebelmail-dashboard/tmp/concat_with_maps-input_base_path-XJShtug2.tmp/0/bower_components/ember-data-model-fragments/dist/ember-data-model-fragments.js'
Error: ENOENT: no such file or directory, stat '/Users/devinus/Projects/rebelmail-dashboard/tmp/concat_with_maps-input_base_path-XJShtug2.tmp/0/bower_components/ember-data-model-fragments/dist/ember-data-model-fragments.js'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at ConcatWithMaps.keyForFile (/Users/devinus/Projects/rebelmail-dashboard/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/devinus/Projects/rebelmail-dashboard/node_modules/broccoli-caching-writer/index.js:112:65)
    at /Users/devinus/Projects/rebelmail-dashboard/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/devinus/Projects/rebelmail-dashboard/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/devinus/Projects/rebelmail-dashboard/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/devinus/Projects/rebelmail-dashboard/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/devinus/Projects/rebelmail-dashboard/node_modules/rsvp/dist/rsvp.js:1198:9)
```

**Comment by slindberg** [comment]
What's the context? `ember serve`? What environment?

**Comment by devinus** [comment]
@slindberg `ember serve`

```
devinus@cutter [01:04:17] [~/Projects/rebelmail-dashboard] [upgrade-deps *]
-> % npm -v
3.3.12
devinus@cutter [01:06:08] [~/Projects/rebelmail-dashboard] [upgrade-deps *]
-> % node -v
v5.1.1
```

**Comment by devinus** [comment]
I've completely cleared every cache as well.

**Comment by workmanw** [comment]
I've had this happen with other CLI addons too after upgrading to the newest Ember-CLI version. The "tmp" directory is maintained even after killing the server. I'm guessing the idea was to make `ember serve` faster on initial load, but it does seem to cause issues like this occasionally (for me at least).

**Comment by slindberg** [comment]
@devinus I'm not able to reproduce this, can try @workmanw's suggestion and `rm -rf tmp`?

**Comment by devinus** [comment]
@slindberg I'm doing `rm -rf tmp dist bower_components node_modules ~/.npm ~/.cache/bower` and still experiencing it. :(

**Comment by slindberg** [comment]
Just for shits and grins, would you mind doing the full nom-bom using npm's and bower's cache clean commands (just to make absolutely sure the caches are cleared)?

```sh
> npm cache clear && bower cache clean && rm -rf tmp node_modules bower_components && npm install && bower install
> ember serve
```

If that doesn't work, post your `npm -ls` so I can diff it against mine. We'll figure this out.

**Comment by devinus** [comment]
STOP THE PRESSES.

This is apparently because I needed to also `bower install --save ember-data-model-fragments#1.13.1`, should this be added to the readme or added as part of the addon setup phase?

**Comment by slindberg** [comment]
Well, that's supposed to happen automatically as part of the [addon blueprint](https://github.com/lytics/ember-data-model-fragments/blob/master/ember-addon/blueprints/ember-data-model-fragments/index.js#L13) (run when doing an `ember install ember-data-model-fragments`). This is the multiple-package-managers issue that ember-cli has been tackling for some time.

I think the goal is to do away with bower at some point, but until then there's no way to ensure Bower and NPM are in sync. The best way forward is probably to build MF as part of the project like [ED recently started to do](https://github.com/emberjs/data/pull/3907), and not require Bower at all. Add it to the TODO list...
