### ISSUE TITLE
Can't rollback fragment after #save failure

### ISSUE THREAD

**Issue by xkb** [lytics/ember-data-model-fragments#177]
Seems to be happening on both object and array fragments. If the adapter's `save` fails, the rollback does cascade down but it doesn't rollback each fragment's attributes.

It's clear that the source of the problem is lack of coverage for `adapterDidError` on the Model but even with that added there would need to be an `inFlight` state which will add a bit of complexity. I can probably work on fixing it but I would like to know the preferred direction to take? Since this use to work fine on `0.4.x` !

Here is a spec for the bug (add to tests/integrations/save_test.js)
```js
test("existing fragments can be rolled back on failed save", function() {
  expect(3);

  var data = {
    name: {
      first: "Eddard",
      last: "Stark"
    },
    addresses: [
      {
        street: "1 Great Keep",
        city: "Winterfell",
        region: "North",
        country: "Westeros"
      }
    ]
  };

  store.push({
    data: {
      type: 'person',
      id: 1,
      attributes: data
    }
  });

  env.adapter.updateRecord = function() {
    return Ember.RSVP.reject({});
  };

  var mrStark, name, address;

  return store.find('person', 1).then(function(person) {
    mrStark = person;

    name = mrStark.get('name');
    address = mrStark.get('addresses.firstObject');

    name.set('first', 'BadFirstName');
    name.set('last', 'BadLastName');
    address.set('street', 'BadStreet');

    return mrStark.save();
  }).catch(function() {
    mrStark.rollbackAttributes();

    equal(`${name.get('first')} ${name.get('last')}`, 'Eddard Stark', "fragment name rolled back");
    equal(address.get('street'), '1 Great Keep', "fragment array fragment correctly rolled back");
  });
});
```

**Comment by JennieJi** [comment]
Met the same problem

**Comment by slindberg** [comment]
Thanks for adding a test :+1: 

I haven't looked into this, but it doesn't sound like there would need to be an `inFlight` state, since changes to fragment properties are stored in `._attributes` like normal `attr`s (doubly so, considering this used to work in 0.4). It sounds like maybe `adapterDidCommit` or `setupData` is getting called on the fragment despite the error. It'd be great if you wanted to work on a fix, I would start there.
