### ISSUE TITLE
Issue with  "ember-data": "1.0.0-beta.16" and  "ember-data-model-fragments": "0.3.3"

### ISSUE THREAD

**Issue by nagkumar** [lytics/ember-data-model-fragments#180]
When using ember data with the following bower dependences

```
{
  "name": "example1",
  "dependencies": {
    "ember": "1.13.11",
    "ember-cli-shims": "0.0.6",
    "ember-cli-test-loader": "0.2.1",
    "ember-data": "1.0.0-beta.16",
    "ember-load-initializers": "0.1.7",
    "ember-qunit": "0.4.16",
    "ember-qunit-notifications": "0.1.0",
    "ember-resolver": "~0.1.20",
    "jquery": "1.11.3",
    "loader.js": "ember-cli/loader.js#3.4.0",
    "qunit": "~1.20.0",
    "ember-data-model-fragments": "0.3.3"
  }
}
```

and start the ember server, it is throwing this error. Pl. advise what is wrong. 

> Error: ENOENT: no such file or directory, stat 'C:\temp\ember_data_fragments\tmp\concat_with_maps-input_base_path-McCNZ0Oh.tmp\0\bower_components\ember-data-model-fragments\dist\ember-data-model-fragments.js'
>     at Error (native)
>     at Object.fs.statSync (fs.js:844:18)
>     at ConcatWithMaps.keyForFile (C:\temp\ember_data_fragments\node_modules\broccoli-caching-writer\index.js:90:20)
>     at Array.map (native)
>     at ConcatWithMaps.CachingWriter._conditionalBuild (C:\temp\ember_data_fragments\node_modules\broccoli-caching-writer\index.js:112:65)
>     at C:\temp\ember_data_fragments\node_modules\broccoli-caching-writer\node_modules\broccoli-plugin\read_compat.js:61:34
>     at lib$rsvp$$internal$$tryCatch (C:\temp\ember_data_fragments\node_modules\rsvp\dist\rsvp.js:493:16)
>     at lib$rsvp$$internal$$invokeCallback (C:\temp\ember_data_fragments\node_modules\rsvp\dist\rsvp.js:505:17)
>     at lib$rsvp$$internal$$publish (C:\temp\ember_data_fragments\node_modules\rsvp\dist\rsvp.js:476:11)
>     at lib$rsvp$asap$$flush (C:\temp\ember_data_fragments\node_modules\rsvp\dist\rsvp.js:1198:9)

**Comment by slindberg** [comment]
The repository and dist files were renamed before the v1.0.0 release from `ember-data.model-fragments` to `ember-data-model-fragments` (dot to slash).

Try making the `ember-data-model-fragments` dependency in `package.json` 0.3.3, otherwise the build will be looking for the updated file names that don't exist.
