### ISSUE TITLE
Using ember-data-factory-guy with model fragments

### ISSUE THREAD

**Issue by mattmcginnis** [lytics/ember-data-model-fragments#185]
I'm wondering if anyone is successfully using model fragments with factory guy.  The main issue I'm running into is with this line in factory guy

```javascript
return container.lookup('transform:' + type).serialize;
```

"type" in my case is "-mf-fragment$fragment.name" which returns an error since there is no transform of that type.

**Comment by whatthewhat** [comment]
I hit the same issue when updating ember-data-factory-guy, did not have time to investigate this properly though.

**Comment by slindberg** [comment]
MF does some [monkey patching of `DS.JSONSerializer`](https://github.com/lytics/ember-data-model-fragments/blob/master/packages/model-fragments/lib/fragments/ext.js#L293-L330) to support fragment-specific transforms, so looking up the transform directly like factory-guy is doing won't work. I don't have the bandwidth for this, but I would suggest opening a PR to factory-guy that changes the line to call `transformFor` on the serializer, like ED does internally. I'm not sure how they will feel about that just to be compatible with this addon, but it's worth a try `¯\_(ツ)_/¯`

**Comment by whatthewhat** [comment]
Asked the question in the factory-guy  repo: https://github.com/danielspaniel/ember-data-factory-guy/issues/182
