### ISSUE TITLE
Tool Suggestion: Ember Models Generator

### ISSUE THREAD

**Issue by nire0510** [lytics/ember-data-model-fragments#193]
Hi all, it's not an issue, but a recommendation for a tool I've created which auto generates models out of a given JSON object, which also includes support for this great addon of yours, the Ember Data Model Fragments:
http://feditor.io/content/gist/6478b5134893399879c0

Thanks!

**Comment by slindberg** [comment]
Hey, this is awesome! [I opened a PR](https://github.com/lytics/ember-data-model-fragments/pull/197) to add a note in the readme about it. Will there be a more permanent URL, or is the gist one good to use?

One thing I did notice is that the fragment models that are generated are missing the import for `MF`:

```js
import MF from 'model-fragments';
```

Thanks for the awesome tool!

**Comment by nire0510** [comment]
Cool!!! so glad you like it :)
The URL i submitted is good enough, but here is a short version of it:
http://goo.gl/qZkTUR

As for the `import` module - no problem, I've updated the code so that this statement will be added to each model file definition (although I haven't used it in any of my projects and yet it worked :-| weird).

Thanks again!

**Comment by slindberg** [comment]
Great, added to readme in #197
