### ISSUE TITLE
TypeError: Converting circular structure to JSON on model.save()

### ISSUE THREAD

**Issue by vedebel** [lytics/ember-data-model-fragments#203]
Got error whent call `model.save()`:  

> TypeError: Converting circular structure to JSON

**some-model.js**
```javascript
'use strict';
import Model from 'ember-data/model';
import attr from 'ember-data/attr';
import { belongsTo } from 'ember-data/relationships';
import {fragment} from 'model-fragments/attributes';

export default Model.extend({
    name: attr('string'),
    serviceId: attr('number', {
        defaultValue: 1
    }),
    product: belongsTo('product', { async: false }),
    active: attr('number'),
    text: attr('string'),
    settings: fragment('some-model-settings', {
        defaultValue: function() {
            return {
                clickPrice: ''
            };
        }
    })
});
```

**some-model-settings.js**
```javascript
Import attr from 'ember-data/attr';
import Fragment from 'model-fragments/fragment';

export default Fragment.extend({
    clickPrice : attr('string', {
        defaultValue: ''
    })
});
```
Can any one help?

**Comment by aars** [comment]
Not sure what's going on, but the `defaultValue: function() {}` is unnecessary. Just use `defaultValue: { clickPrice: '' }` in this case.

Are you sure it's a model-fragments issue? Can you `model.save()` without the `settings` attribute in `some-model.js`?

**Comment by vedebel** [comment]
Yes, its not necessary. Just twrote so =)

If is set `settings: attr()` everything works fine.

**Comment by aars** [comment]
I think you'll have to post a bit more info on the error. File. line-number, etc. Is this the *actual* code you're using?

I have a very similar setup that works just fine. Same Ember, Ember Data and Model Fragments versions.  Here's one similar to yours:

```
// app/models/some-model.js
...
cancellation: MF.fragment('fragments/cancellation', {
    defaultValue: {
      enabled: true,
      days: 30
    }
  }),
...

// app/models/fragments/cancellation.js
export default MF.Fragment.extend( {
  enabled: DS.attr('boolean'),
  days: DS.attr('number')
});
```

Do you have any customization in your Serializer(s)?

**Comment by vedebel** [comment]
Well... Thanks for reply. I checked out my applicayionSerializer and have custom serialize method there which brakes code.
