### ISSUE TITLE
Way to allow fragments to also be models

### ISSUE THREAD

**Issue by djsegal** [lytics/ember-data-model-fragments#204]
Let's say I have a form that has deeply nested forms in it, can I treat each level of form as a fragment in some cases and a model in others?

**Comment by slindberg** [comment]
I'm not sure how to answer this question without more information. On the surface, it sounds like it's an app-domain problem, but maybe I'm misunderstanding. At a high level, if you are only calling methods/using properties that are common to both fragments and records, there's no reason you can't do you what you're describing. The differences between the fragment and model APIs are minimal: basically fragments don't have methods for persistence, e.g. `.save()`

**Comment by djsegal** [comment]
I just solved the issue by having a `exampleForm` model and `exampleForm` fragment, where

**Comment by slindberg** [comment]
Still don't think I fully understand the problem, but if you found a solution, great! 😎
