### ISSUE TITLE
`StatefulArray` is broken with Ember 2.8.

### ISSUE THREAD

**Issue by workmanw** [lytics/ember-data-model-fragments#209]
See my comment here: https://github.com/emberjs/ember.js/pull/13534#issuecomment-241293324

Not sure yet what the best course of action is there. Hopefully we can get a response there and can figure out where to go from there. 

Edit: Now an issue open in Ember: https://github.com/emberjs/ember.js/issues/14114.

**Comment by workmanw** [comment]
Just an update, Martin was kind enough to open a PR to help resolve this issue for Ember 2.8: https://github.com/emberjs/ember.js/pull/14117

**Comment by jakesjews** [comment]
@workmanw glad to hear it! Should we close this issue or will there be some changes we will need to make later?

**Comment by workmanw** [comment]
@jakesjews I'd prefer to leave this issue open until this that PR is merged and ember cuts a new beta ... just incase someone actually tries the ember-beta and runs into this issue. 

In terms of making changes, I do think we'll have to make some changes in the near future (post ember 2.8 LTS). But I'll keep a watchful eye on it!

**Comment by jakesjews** [comment]
@workmanw sounds good. Thanks for looking into the issue.

**Comment by workmanw** [comment]
A new beta version was just released yesterday. Tested with `ember try:each` and can confirm all tests pass on all supported versions of ember.
