### ISSUE TITLE
Polymorphic fragment not working

### ISSUE THREAD

**Issue by basz** [lytics/ember-data-model-fragments#213]
Hi I'm trying to work with a polymorphic fragment. I followed the instruction from the read me as close as possible but I can figure it out.

I would appreciate very much it it your could have a look at this demo repo: https://github.com/basz/ember-data-fragment-test

The Ember inspector did show four animals, but no loins or elephants at some point, now it simply stays 0. The template does render four animals...

**Comment by basz** [comment]
I figured out why this was not working.... :-) 

Turns out that unless you defined the typeKey as field on the parent class it does not work...

I'll create a PR to update the docs.

**Comment by jakesjews** [comment]
Closing since this was resolved by #214
