### ISSUE TITLE
Doesn't work with Ember Twiddle

### ISSUE THREAD

**Issue by benoror** [lytics/ember-data-model-fragments#217]
When using in Ember Twiddle the following error is shown:

> Uncaught Error: Could not find module `ember-data/-private/system/model/internal-model` imported from `model-fragments/ext`

Example: https://ember-twiddle.com/3fcebcb56194127c97cb64dde1d420ad?openFiles=models.foo.js%2C

**Comment by jakesjews** [comment]
This could be a tricky one. I'm betting that ember-twiddle doesn't allow importing from private apis or something along those lines. I'll try to take a deeper look when I get a chance.

**Comment by workmanw** [comment]
@benoror I opened [ember-cli/ember-twiddle#531](https://github.com/ember-cli/ember-twiddle/issues/531) and it does seem like this is an issue with ember-twiddle. I'm going to leave this open for a period of time until we know which way it goes. But I actually have a backup plan to make this work.

**Comment by workmanw** [comment]
Hey great news! @Gaurav0 was able to restructure ember-twiddle in a way that allows ember-data-model-fragments to work. 🎉 🎉 🎉 🎉 🎉
