### ISSUE TITLE
Request to patch 2.1 with the toStringExtension bug fix in 2.3

### ISSUE THREAD

**Issue by DingoEatingFuzz** [lytics/ember-data-model-fragments#220]
On v2.1.2 I ran into the `toStringExtension` bug that @jakesjews and @cesarizu have both addressed [here](https://github.com/lytics/ember-data-model-fragments/blob/master/addon/fragment.js#L129-L135).

Since the upgrade from Ember and ED 2.2 to 2.3 is non-trivial, I figured it would be better to publish the fix for this bug rather than leapfrogging releases myself and expecting that out of other MF consumers.

Before pushing a v2.1.3 patch with this change in it, I wanted to run it past other contributors.

[Diff](https://github.com/lytics/ember-data-model-fragments/compare/v2.1.2...back-patch-fragment-to-string-extension)

**Comment by jakesjews** [comment]
I'm ok with this. @workmanw what do you think?

**Comment by workmanw** [comment]
@DingoEatingFuzz @jakesjews Yeap, I'm definitely okay with this. I think the easiest solution here is for me to just suck your commit into the repo and tag it up from there. Since we don't have a 2.1.x branch. Thoughts? Objections?

**Comment by DingoEatingFuzz** [comment]
Sounds good to me 👍

**Comment by cesarizu** [comment]
:+1:

**Comment by workmanw** [comment]
@DingoEatingFuzz Oh, I bet my response sounded silly. I didn't realize you were a lytics member and that branch was already in this repo (I thought it was a diff in your repo). D'oh, my mistake! 

So yea, I went ahead and added a "release commit" to the end of your commits and tagged it up [`v2.1.3`](https://github.com/lytics/ember-data-model-fragments/tree/v2.1.3). 

Sorry for the confusion. I didn't pay enough attention. I definitely appreciate the fact that you opened this issue to bring it up for discussion. 👍 💯 

Lastly, would you like an `npm release` for this patch version? @jakesjews is that something you can do?

**Comment by jakesjews** [comment]
@workmanw not quite yet I still need to get in touch with @slindberg about getting access to it. I've been pretty crushed at work lately so I haven't had time to do it yet although I would like to sooner rather than later to get a new release out.

**Comment by DingoEatingFuzz** [comment]
I'm actually a contributor for the project on npm. I can do the `npm release`.

**Comment by DingoEatingFuzz** [comment]
Okay. 2.1.3 is now published to npm. @workmanw, I force pushed a new version of the v2.1.3 tag that also bumps the patch in `bower.json`.

Thanks everyone.

**Comment by workmanw** [comment]
@DingoEatingFuzz Excellent! Thank you for that. I had forgotten that `< 2.3.x` used bower.json.

**Comment by jreading** [comment]
Is the version number correct in the NS register?
