### ISSUE TITLE
Fragment stays dirty after parent, which is embedded record, is saved

### ISSUE THREAD

**Issue by MartinMalinda** [lytics/ember-data-model-fragments#221]
I have a following data structure:

Grid Item:
```javascript
export default Fragment.extend({
  grid: inject.service(),
  offset: 22,

  x: attr('number'),
  y: attr('number'),
  on: attr('boolean', {defaultValue: true}),
  space: attr('number', {defaultValue: 1}),
  orientation: attr('string', {defaultValue: 'landscape'}),
```

Layout model mas many gridItems:
```javascript
gridItems: fragmentArray('grid-item'),
```

Layout is embedded within project model:
```javascript
layouts: hasMany('layout', {
    async: false
}),
// project serializer
export default ActiveModelSerializer.extend(DS.EmbeddedRecordsMixin, {
  isNewSerializerAPI: true,
  attrs: {
    layouts: {
      embedded: 'always'
    }
  },
```

The issue is, that when I do `project.save()`, grid items stay dirty. (`hasDirtyAttributes` keep being true). Maybe I am mixing two concepts here and I should use embedded records for everything or fragments for everything. But server expects IDs for layouts and regular arrays of json for grid items. So I thought this was sufficient.

**Comment by MartinMalinda** [comment]
Will try to set up a test repo later when I find some extra time.

**Comment by workmanw** [comment]
Hey @MartinMalinda . Any luck on this? Were you able to create a reproduction of this?

**Comment by MartinMalinda** [comment]
@workmanw I think this issue can be closed. It is most likely not issue with model-fragments but with ember-data. The app I was maintaining back then had issues with duplicate records (emberjs/data#1829). It had some workaround solution that cleared the duplicate but that also probably created the issues with dirtiness.

**Comment by workmanw** [comment]
@MartinMalinda Awesome! Thanks for the update. I will close it.
