### ISSUE TITLE
Release ember 2.3.3 to npm.

### ISSUE THREAD

**Issue by workmanw** [lytics/ember-data-model-fragments#231]
I'm going to give this a go today. CC: @jakesjews.

**Comment by jakesjews** [comment]
Sounds good @workmanw

**Comment by workmanw** [comment]
BTW I was able to easily publish this new version with `npm publish`. See: https://www.npmjs.com/package/ember-data-model-fragments

CC: @DingoEatingFuzz Thanks again.
