### ISSUE TITLE
Remove fragment from fragment array?

### ISSUE THREAD

**Issue by lbblock2** [lytics/ember-data-model-fragments#233]
HI, I've been having issues removing fragments from a fragment array using Ember Data 2.7 and Ember Data Model Fragments 2.3.2.

If you have a structure as such:
```
{
  "person": {
    "id": "1",
    "name": {
      "first": "Tyrion",
      "last": "Lannister"
    },
    "addresses": [
      {
        "street": "1 Sky Cell",
        "city": "Eyre",
        "region": "Vale of Arryn",
        "country": "Westeros"
      },
      {
        "street": "1 Tower of the Hand",
        "city": "King's Landing",
        "region": "Crownlands",
        "country": "Westeros"
      }
    ],
    "titles": [ "Imp", "Hand of the King" ]
  }
}
```

and we want to remove one of the addresses, how does one do that? Is it necessary to remove the address specifically from the `person.addresses` since the `belongsTo` and `hasMany` are not fully implemented? Thanks!

**Comment by jakesjews** [comment]
You will need to use removeObject on the array

**Comment by lbblock2** [comment]
Thank you. I was using `removeFragment(this)` but neither works. I overwrote `destroyRecord` to get the owner (i.e. `owner = address.get('_internalModel._owner')`) and then `owner.get('addresses').removeFragment(address)`.

This is all called when I call `address.destroyRecord()`. I replaced `removeFragment` with `removeObject` based on the comment, but the behavior is identical.

**Comment by jakesjews** [comment]
Could you put up a git repo demonstrating the issue? Then I can debug it

**Comment by lbblock2** [comment]
Thanks; I resolved the issue. It was related to a deeper level of code.
