### ISSUE TITLE
fragment ready/initialized callback

### ISSUE THREAD

**Issue by JackCA** [lytics/ember-data-model-fragments#250]
hi folks,

I have been trying to figure out a way to do some initialization after a fragment has been created.

Here is pseudocode:

```javascript
//parent
export default DS.Model.extend({
  items: fragmentArray('item')
});

// child

export default MF.Fragment.extend({
  init() {
    this._super(...arguments);
    this.get('foo') //null
    this.get('owner') //null
  },

  ready() {
    //never called
  }
})


parentInstance.get('items').createFragment({ foo: 'bar' });
```

The main issue is that in `init`, I don't have access to either the directly passed argument `foo` or the implicit `owner`.

I also thought that may not be the right callback, and attempted to use ember-data's `ready` callback but it never gets called here.

I believe these two behaviors differ from ember-data.

Is there a proper callback to use so that I can access explicit attributes and the owner after initialization?

**Comment by JackCA** [comment]
and now I'm seeing that `owner` is not a public attribute. Is this correct?

**Comment by workmanw** [comment]
I suspect you're referring to Ember's `owner` they use for instance management and dependency injection? If so, you should use `Ember.getOwner(this)` to look it up.

With regards to the properties not being available on `init`. Are you sure it works this way in ember-data? I thought that there internals did not make this possible. 

With regards to `ready` ... To be honest I didn't even know `ready` existed. So if it this doesn't work, it's probably a bug that we should fix.

**Comment by JackCA** [comment]
@workmanw sorry, I don't know why I assumed there would be an `owner` property on a fragment. 

What I'm referring to is being able to access the fragment's "owner" or "parent". The only way I see to do this now is via `_internalModel._owner`. Is there a better way to access that? Sorry for the confusion.

In regards to init: I think you are right in that I just tried to do what I suggested in Ember Data itself, and I was unable to access the arguments.

However, (in regard to `ready`), it does have access to the attributes, so I think it is in fact the callback I'm looking for.

fwiw, I didn't know about `ready` either :/

**Comment by jakesjews** [comment]
@JackCA you can access the fragment owner with https://github.com/lytics/ember-data-model-fragments/blob/158a12f5d7adb24be1a22310402b58b10e584349/addon/attributes.js#L330

**Comment by JackCA** [comment]
@jakesjews awesome, thank you. Should I make a PR to add that to the top-level README?

That solves the access to owner question I have, but still open to discussing the initialization callback

**Comment by jakesjews** [comment]
A PR would be cool. I'll take a look into the initialization problem when I get some more free time

**Comment by danielspaniel** [comment]
Curious about this same topic myself. 
 https://emberjs.com/api/data/classes/DS.Model.html  shows the list of events 
 The main ones for most purposes are didLoad or ready
 Want me to noodle around and try and hook this up?

**Comment by workmanw** [comment]
I believe @danielspaniel's PR closed this issue. If I'm wrong, let me know and I will reopen.
