### ISSUE TITLE
Assertion Failed: The `JSONAPISerializer` is not suitable for model fragments, please use `JSONSerializer`

### ISSUE THREAD

**Issue by jamesdixon** [lytics/ember-data-model-fragments#256]
Hi,

I know this has already been brought up in #140, but it's been surfacing for me ever since switching to 2.11. It seems to happen periodically and I'm not sure why.

Thanks in advance!

**Comment by jamesdixon** [comment]
Note: I'm running Ember/Ember Data 2.11.3.

**Comment by workmanw** [comment]
Are you using ember-data-model-fragments v2.11.2 ? If so, can you provide more details to reproduce?

**Comment by jamesdixon** [comment]
@workmanw I am, but having trouble reproducing this now. It's an odd situation. I'll close this for now and keep you posted if it occurs again.

Cheers.
