### ISSUE TITLE
Ember Data 2.12  Passing classes to store methods has been removed

### ISSUE THREAD

**Issue by vyobukhov** [lytics/ember-data-model-fragments#257]
Hi!
I've accidentally updated my ember-data to 2.12 and got this message:
"Assertion Failed: Passing classes to store methods has been removed. Please pass a dasherized string instead of client@model:collection/section:"

My model:
```javascript
export default DS.Model.extend({
  sections:  MF.fragmentArray('collection/section')
});
```

P.S. I know 2.12 was released just two days ago, so I rolled back to 2.11 and everything is fine now, but hope my issue will help to fix this.

**Comment by jakesjews** [comment]
@vyobukhov what version of model-fragments are you using? I think this was resolved in a recent update.

**Comment by vyobukhov** [comment]
@jakesjews Thx, 2.11.2 works fine. I was using 2.11.0.

**Comment by workmanw** [comment]
@vyobukhov Awesome. Glad to hear it!
