### ISSUE TITLE
"Uncaught TypeError: Converting circular structure to JSON"

### ISSUE THREAD

**Issue by erkie** [lytics/ember-data-model-fragments#259]
I have a fairly complex fragment model that upon successful save throws the error `Uncaught TypeError: Converting circular structure to JSON`.

Here is a screenshot of the place it occurs:

![screenshot 2017-04-05 16 16 34](https://cloud.githubusercontent.com/assets/21059/24709841/8fa9ca24-1a1b-11e7-83f9-61952bf2437b.png)

Here is the stacktrace:

![screenshot 2017-04-05 16 19 10](https://cloud.githubusercontent.com/assets/21059/24709893/aedbdf0e-1a1b-11e7-99b3-a3c09c9307a4.png)

Sorry for the images, it was the easiest way I could think to share the most info. I am working on a demo project to reproduce this issue. It seems to happen because `this._inFlightAttributes` is using not `JSON.stringify`-able. The model itself is a `Fragment.extend` model with many nested `fragment`/`fragmentArray` and regular DS.attr properties.

Using the latest stable Ember (2.12) and the latest release of `ember-data-model-fragments`.

**Comment by jakesjews** [comment]
@erkie I've actually been hitting the same issue with nested fragments but haven't had a chance to make a PR yet. I'm fairly certain its from https://github.com/lytics/ember-data-model-fragments/pull/247 but I can't revert it since it fixes a different issue.

**Comment by humanchimp** [comment]
We're seeing this one too. It seems like `JSON.stringify` is being used as a "hashing" function to compare object "equality". If we really need that deep comparison, we should use a technique that can handle cycles.

**Comment by workmanw** [comment]
I certainly don't doubt this is happening, but I'm having a hard time imagine a scenario for this. It seems for this to happen a fragment would have to have an ancestor fragment that is also a child. Can someone help me understand the data model that reproduces this?

**Comment by humanchimp** [comment]
I'll try to cobble together a minimal reproduction

**Comment by erkie** [comment]
I was able to reproduce this by adding a `fragmentArray` to a nested `fragment`. This branch fails the same way we are seeing in production:

https://github.com/lytics/ember-data-model-fragments/compare/master...erkie:cyclic-json-error

**Comment by humanchimp** [comment]
At least one cycle in that example is
`original.name.animals.owner._internalModel._fragments.animals === original.name.animals`

**Comment by coachTomato** [comment]
Unfortunately we got into trouble to upgrade to current ember cli version, because of this issue. Are there any ideas to solve the problem?

**Comment by nk1g13** [comment]
Hitting the same issue. I have nested fragments structure:

```
// Main model 
export default Model.extend({
    someId:     attr('number'),
    groups:      fragmentArray('group-item')
});

// group-item.js
export default Fragment.extend({
    name:         attr('string'),
    active:        attr('boolean', { defaultValue: false })
    patterns:      fragmentArray('pattern')
});

// pattern.js
export default Fragment.extend({
    one:     attr('string', { defaultValue: null }),
    two:     attr('string', { defaultValue: null }),
    three:   attr('string', { defaultValue: null }),
});
```

The issue appear when I make changes in group-item fragment and trying to save the changes. Would like to notice that everything is updating correctly, but error is appear in console:
![screen shot 2017-05-09 at 4 43 49 pm](https://cloud.githubusercontent.com/assets/6682190/25853959/1d1387b2-34d7-11e7-81f0-68974e5e9410.png)

**Comment by jakesjews** [comment]
@workmanw would you be ok with reverting https://github.com/lytics/ember-data-model-fragments/pull/247 until we come up with a better solution for the alias problem?

**Comment by workmanw** [comment]
@jakesjews Yea, I am.

**Comment by jakesjews** [comment]
@workmanw cool I'll revert it when I get out of work later today

**Comment by nk1g13** [comment]
Thanks @workmanw and @jakesjews

**Comment by coachTomato** [comment]
Yeah, that's great! 👍

**Comment by patocallaghan** [comment]
@workmanw @jakesjews just wondering if there are any plans to do a new release with this fix?
