### ISSUE TITLE
Broken method "_changedKeys" in "2.11.3"

### ISSUE THREAD

**Issue by Hurtsok** [lytics/ember-data-model-fragments#268]

**Comment by Hurtsok** [comment]
Hey! When i update package from 2.3 to 2.11.3 i receive and error when trying to save model "Converting circular structure to JSON at JSON.stringify" problem is here [https://github.com/lytics/ember-data-model-fragments/blob/v2.11.3/addon/ext.js#L301](url).
And I found that this commit which will probably fix this is not released from master branch [https://github.com/lytics/ember-data-model-fragments/commit/e3c8b6c73f85d05772c2844620b31ebd18ea0e19](url)
Am I right?

**Comment by workmanw** [comment]
@Hurtsok Yes, all of that sounds correct to me. I'll be making a new release within the next week. I was hoping to get #266 resolved first.

**Comment by Hurtsok** [comment]
Thank you a lot.

**Comment by workmanw** [comment]
@Hurtsok 2.11.4 has been released.
