### ISSUE TITLE
Could not find private ember data module

### ISSUE THREAD

**Issue by gwak** [lytics/ember-data-model-fragments#271]
Hi,

I've just tried to install a fresh Ember app and installed ember-data-model-fragments.

Here's my package.json:
```json
{
  "name": "ember213",
  "version": "0.0.0",
  "description": "Small description for ember213 goes here",
  "license": "MIT",
  "author": "",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": "",
  "scripts": {
    "build": "ember build",
    "start": "ember server",
    "test": "ember test"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^3.0.0",
    "ember-cli": "2.13.2",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.0.0",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-eslint": "^3.0.0",
    "ember-cli-htmlbars": "^1.1.1",
    "ember-cli-htmlbars-inline-precompile": "^0.4.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-qunit": "^4.0.0",
    "ember-cli-shims": "^1.1.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-data": "^2.13.0",
    "ember-data-model-fragments": "^2.11.5",
    "ember-export-application-global": "^2.0.0",
    "ember-load-initializers": "^1.0.0",
    "ember-resolver": "^4.0.0",
    "ember-source": "~2.13.0",
    "ember-welcome-page": "^3.0.0",
    "loader.js": "^4.2.3"
  },
  "engines": {
    "node": ">= 4"
  },
  "private": true
}
```
When I `ember serve` , the app builds fine it seems but I get the following error:

Uncaught Error: Could not find module `ember-data/-private/system/model/internal-model` imported from `ember-data-model-fragments/ext`

Could you please help ?

Thanks,
Camille

**Comment by jakesjews** [comment]
@gwak it looks like ember data 2.14 is being pulled in from the semver caret. There is a WIP PR to update model-fragments for 2.14 compatibility https://github.com/lytics/ember-data-model-fragments/pull/270. In the meantime you can change the ^ to a ~ in package.json and it should fix it for now.

**Comment by workmanw** [comment]
Yeap, I can confirm this. We're just waiting on ember 2.14 to ship because we only support lock step ember and ember-data versions.

**Comment by gwak** [comment]
Oh, of course, great thanks ! It works now. I'm closing this issue.
