### ISSUE TITLE
Ember-Data 2.15 compatibility

### ISSUE THREAD

**Issue by chrisgame** [lytics/ember-data-model-fragments#279]
When running against ember data 2.15 i'm getting 
Uncaught Error: Could not find module `ember-data/-private/system/model/internal-model` imported from `ember-data-model-fragments/ext`

I'm using ember 2.15 as well

**Comment by jakesjews** [comment]
Which version of model fragments are you using? Compatibility with ember data 2.14+ was added in 2.14

**Comment by chrisgame** [comment]
2.14 i thought, double checking

**Comment by chrisgame** [comment]
my bad, cleared everything down and tried again and it worked like a dream. Sorry for wasting your time.
