### ISSUE TITLE
Tracking issue for removal of `ContainerInstanceCache`

### ISSUE THREAD

**Issue by rwjblue** [lytics/ember-data-model-fragments#285]
I just proposed a simplification for Ember Data, which removes the usage of `ContainerInstanceCache`.  This would be a breaking change to ember-data-model-fragments, so I wanted to open an issue proactively so we can track things...

See https://github.com/emberjs/data/pull/5300

**Comment by rondale-sc** [comment]
Just ran into this.  Looks like at the moment ConstainterInstanceCache is used in the ED extensions: 

https://github.com/lytics/ember-data-model-fragments/blob/c7a57b3ee2d75287a395c49830e84b26d4ddfc70/addon/ext.js#L323

**Comment by rondale-sc** [comment]
@rwjblue I believe this can be closed by:

https://github.com/lytics/ember-data-model-fragments/pull/287 

Can you confirm. :beers:

**Comment by workmanw** [comment]
Bump. @rwjblue Can you take a quick peak and confirm this was resolved by @rondale-sc ? Should be a 5 second look.

**Comment by workmanw** [comment]
Closing based on @rwjblue's comment in #287.
