### ISSUE TITLE
Ready for non-beta 3.x

### ISSUE THREAD

**Issue by danwenzel** [lytics/ember-data-model-fragments#289]
Since ember-data 3.0 is officially out, can we release a non-beta version?

**Comment by danwenzel** [comment]
@workmanw - Since https://github.com/lytics/ember-data-model-fragments/pull/291 has been merged, can we get a new release out?

**Comment by workmanw** [comment]
#293

**Comment by danwenzel** [comment]
🎉  Thanks!
