### ISSUE TITLE
3.0.0 beta - In Production, null exception when saving object

### ISSUE THREAD

**Issue by maxzats** [lytics/ember-data-model-fragments#290]
on ember-data 3.0.1, ember 3.0.0, and model-fragments 3.0.0-beta.1

```
TypeError: Cannot read property 'replace' of null
    at e.func (vendor.js:2892)
    at e.get (vendor.js:2132)
    at S (vendor.js:2896)
    at e.func (vendor.js:2890)
    at e.get (vendor.js:2132)
    at Object.k [as dasherize] (vendor.js:2896)
    at _ (vendor.js:9743)
    at o.modelFactoryFor (vendor.js:10157)
    at e.getRecord (vendor.js:9937)
    at o.createFragment (vendor.js:9337)
```

Can't recreate it on dev mode. Any ideas?

Downgrading to Ember Data 2.17 and model-fragments 2.14 works

**Comment by jakesjews** [comment]
I think i've encountered the same issue. I'll try to take a look when I get a chance.

**Comment by maxzats** [comment]
Hey @jakesjews have you been able to take a look?

**Comment by jakesjews** [comment]
Hey @maxzats I just made https://github.com/lytics/ember-data-model-fragments/pull/291 to get a baseline going so I can look deeper with all the 3.0 versions. After that gets merged in it should be easier to track down the problem

**Comment by maxzats** [comment]
@jakesjews great, any ETA on when that'd be merged so we can track down the null pointer?

**Comment by jakesjews** [comment]
@maxzats once my co-maintainer says the PR looks cool I can merge it in.

**Comment by maxzats** [comment]
@jakesjews looks like it was approved & merged. any way i can help to track this down?

**Comment by jakesjews** [comment]
@maxzats I just tried running an application with latest ember, ember-data, and model fragments beta and the issue doesn't seem to be happening for me anymore. Can you try again with the latest versions of everything to see if its still happening for you?

**Comment by dusanstanojeviccs** [comment]
@jakesjews I work in the same team as Max and I am still running into this issue in production. Here is the stack trace:

```
TypeError: Cannot read property 'replace' of null
    at e.func (vendor-d31263a52e18fbb932a63525ccde7364.js:2892)
    at e.get (vendor-d31263a52e18fbb932a63525ccde7364.js:2132)
    at S (vendor-d31263a52e18fbb932a63525ccde7364.js:2896)
    at e.func (vendor-d31263a52e18fbb932a63525ccde7364.js:2890)
    at e.get (vendor-d31263a52e18fbb932a63525ccde7364.js:2132)
    at Object.k [as dasherize] (vendor-d31263a52e18fbb932a63525ccde7364.js:2896)
    at k (vendor-d31263a52e18fbb932a63525ccde7364.js:9763)
    at o.modelFactoryFor (vendor-d31263a52e18fbb932a63525ccde7364.js:10190)
    at e.getRecord (vendor-d31263a52e18fbb932a63525ccde7364.js:9956)
    at o.createFragment (vendor-d31263a52e18fbb932a63525ccde7364.js:9340)
Ember.onerror @ frontend-cc15e6a26f0178315d277fc267830304.js:5
e._run @ vendor-d31263a52e18fbb932a63525ccde7364.js:1310
e._join @ vendor-d31263a52e18fbb932a63525ccde7364.js:1309
e.join @ vendor-d31263a52e18fbb932a63525ccde7364.js:1278
Qe.join @ vendor-d31263a52e18fbb932a63525ccde7364.js:2200
e.handler @ vendor-d31263a52e18fbb932a63525ccde7364.js:1795
(anonymous) @ vendor-d31263a52e18fbb932a63525ccde7364.js:2988
dispatch @ vendor-d31263a52e18fbb932a63525ccde7364.js:254
g.handle @ vendor-d31263a52e18fbb932a63525ccde7364.js:249
frontend-cc15e6a26f0178315d277fc267830304.js:5 Uncaught TypeError: Cannot read property 'replace' of null
    at e.func (vendor-d31263a52e18fbb932a63525ccde7364.js:2892)
    at e.get (vendor-d31263a52e18fbb932a63525ccde7364.js:2132)
    at S (vendor-d31263a52e18fbb932a63525ccde7364.js:2896)
    at e.func (vendor-d31263a52e18fbb932a63525ccde7364.js:2890)
    at e.get (vendor-d31263a52e18fbb932a63525ccde7364.js:2132)
    at Object.k [as dasherize] (vendor-d31263a52e18fbb932a63525ccde7364.js:2896)
    at k (vendor-d31263a52e18fbb932a63525ccde7364.js:9763)
    at o.modelFactoryFor (vendor-d31263a52e18fbb932a63525ccde7364.js:10190)
    at e.getRecord (vendor-d31263a52e18fbb932a63525ccde7364.js:9956)
    at o.createFragment (vendor-d31263a52e18fbb932a63525ccde7364.js:9340)
(anonymous) @ vendor-d31263a52e18fbb932a63525ccde7364.js:2892
e.get @ vendor-d31263a52e18fbb932a63525ccde7364.js:2132
S @ vendor-d31263a52e18fbb932a63525ccde7364.js:2896
(anonymous) @ vendor-d31263a52e18fbb932a63525ccde7364.js:2890
e.get @ vendor-d31263a52e18fbb932a63525ccde7364.js:2132
k @ vendor-d31263a52e18fbb932a63525ccde7364.js:2896
k @ vendor-d31263a52e18fbb932a63525ccde7364.js:9763
modelFactoryFor @ vendor-d31263a52e18fbb932a63525ccde7364.js:10190
e.getRecord @ vendor-d31263a52e18fbb932a63525ccde7364.js:9956
createFragment @ vendor-d31263a52e18fbb932a63525ccde7364.js:9340
copy @ vendor-d31263a52e18fbb932a63525ccde7364.js:9360
e.default @ vendor-d31263a52e18fbb932a63525ccde7364.js:2669
btnClick @ frontend-cc15e6a26f0178315d277fc267830304.js:2011
send @ vendor-d31263a52e18fbb932a63525ccde7364.js:2962
n @ vendor-d31263a52e18fbb932a63525ccde7364.js:2920
triggerAction @ vendor-d31263a52e18fbb932a63525ccde7364.js:2805
sendAction @ vendor-d31263a52e18fbb932a63525ccde7364.js:2960
btnClick @ frontend-cc15e6a26f0178315d277fc267830304.js:777
send @ vendor-d31263a52e18fbb932a63525ccde7364.js:2962
n @ vendor-d31263a52e18fbb932a63525ccde7364.js:2920
(anonymous) @ vendor-d31263a52e18fbb932a63525ccde7364.js:1796
e.flaggedInstrument @ vendor-d31263a52e18fbb932a63525ccde7364.js:2193
(anonymous) @ vendor-d31263a52e18fbb932a63525ccde7364.js:1796
e._run @ vendor-d31263a52e18fbb932a63525ccde7364.js:1310
e._join @ vendor-d31263a52e18fbb932a63525ccde7364.js:1309
e.join @ vendor-d31263a52e18fbb932a63525ccde7364.js:1278
Qe.join @ vendor-d31263a52e18fbb932a63525ccde7364.js:2200
e.handler @ vendor-d31263a52e18fbb932a63525ccde7364.js:1795
(anonymous) @ vendor-d31263a52e18fbb932a63525ccde7364.js:2988
dispatch @ vendor-d31263a52e18fbb932a63525ccde7364.js:254
g.handle @ vendor-d31263a52e18fbb932a63525ccde7364.js:249
```

**Comment by jakesjews** [comment]
@dusanstanojeviccs which versions of ember and ember data is this with?

**Comment by maxzats** [comment]
@jakesjews Ember: 3.0.0, and Ember-Data: 3.1.1

**Comment by jakesjews** [comment]
@maxzats im not able to replicate the issue anymore so If theres some code I can run to replicate it then it would help a ton

**Comment by maxzats** [comment]
@jakesjews it happens very sporadically and under ambiguous circumstances. doesn't even happen in the same place in different user accounts. we have no idea what triggers it, and we've looked into it a bunch. we're just creating a fragment, adding it to a parent object in an array, and saving it.

**Comment by maxzats** [comment]
@jakesjews if we can reproduce it on one of our dev machines would you be interested in screen sharing in and taking a look?

**Comment by jakesjews** [comment]
@maxzats yeah thats cool. I'm doing some traveling this weekend but i can next week sometime

**Comment by deverstalmage** [comment]
@maxzats @jakesjews I ran into this issue as well. For our app it happens when you create a record with a fragment array, but only if the app is built for a production environment. If you run the app locally with a development build the issue does not manifest.

**Comment by maxzats** [comment]
@deverstalmage correct - that's the behavior we're seeing as well.

**Comment by maxzats** [comment]
@jakesjews any ideas on how we can get to a fix on this? it's still blocking our update to ember-data 3

**Comment by jakesjews** [comment]
@maxzats heres the plan so far. Model Fragments is broken with the latest ember-data beta so a full rewrite is happening in the very near future. I'm currently coordinating with the ember-data team on it so hopefully it wont take too long. It will most likely fix these issues cropping up.

**Comment by maxzats** [comment]
@jakesjews will the api be backward compatible?

**Comment by jakesjews** [comment]
@maxzats yeah

**Comment by maxzats** [comment]
@jakesjews awesome. any eta? would like to migrate to ember-data 3 asap

**Comment by JosephHalter** [comment]
+1 still happens when doing a deep copy with Ember.copy(true) of polymorphic fragments, same exact stack trace, also happens only in production

**Comment by maxzats** [comment]
Yep, still preventing us from upgrading to Ember-Data 3.x. Would love a fix for this so we can stay on top of the release cycle. @jakesjews

**Comment by jakesjews** [comment]
Im afraid I'm actually at a bit of a loss for how to debug this issue since I'm not really able to replicate it. I will quickly be able to review any PRs fixing the issue but I'm not actually sure how to fix it myself.

**Comment by maxzats** [comment]
@jakesjews are you able to create a fragment, call Ember.copy() on it, then attach it to a parent and invoke save() on it in a project built in production mode via Ember-CLI? This should help reproduce.
