### ISSUE TITLE
Error when setting array fragment to null

### ISSUE THREAD

**Issue by Techn1x** [lytics/ember-data-model-fragments#306]
I get an error on the following line;
https://github.com/lytics/ember-data-model-fragments/blob/master/addon/attributes.js#L321
(`fragments` is null so `get(fragments,'hasDirtyAttributes')` spits out an error)

The error seems to occur silently, so I had to step through the code to to that point to get it to happen.

Basically, on my edit form, when I go to save changes to the report model, I iterate over each attribute and determine if it needs to stay or be cleared, before sending the request to the server. I set the attr to null like this;

```
// NOTE: Can't set model fragment array attributes to undefined, so must set to null
reportModel.get('reportParams').set('operators', null);
```

Setting any of the array attributes to null seems to cause the error. Below is my model and fragment code

**//app/models/report.js**
```javascript
export default DS.Model.extend({
  reportParams: fragment('reportParams', {
    defaultValue() {
      return {
        assets: [],
        operators: [],
        categories: [],
        duration: moment.duration(6,'hours'),
      };
    }
  }),
});
```

**//app/models/report-params.js**
```javascript
export default Fragment.extend({
	assets: array('string'),
	operators: array('string'),
	categories: array('string'),
	duration: DS.attr('momentDuration')
});
```

**Comment by Techn1x** [comment]
I'm not too familar with this addon, but I think changing the if statement line in attributes.js to this would probably fix it. I am happy to submit a PR but I would like some confirmation
`if (internalModel._data[key] !== fragments || (fragments && get(fragments, 'hasDirtyAttributes')))`

**Comment by jakesjews** [comment]
Sounds good @Techn1x Ill be quick to review any PR

**Comment by Techn1x** [comment]
Submitted the PR with (I think) a working test. I also realised I could avoid this issue in my own code by doing the code below, but have submitted the PR anyway in case anyone else runs into this
```javascript
// only clear if not already null/undefined
if(!isNone(reportModel.get('reportParams').get('operators'))) reportModel.get('reportParams').set('operators', null);
```
