### ISSUE TITLE
Alpha release w/ember-data 3.5+ support?

### ISSUE THREAD

**Issue by XaserAcheron** [lytics/ember-data-model-fragments#325]
Now that #324 has landed (awesome work btw, @cohitre !), would y'all consider cutting an alpha release with the new changes?

I've updated my own project's dependency to point at the latest commit (works great for me w/ember-data 3.7), but it might be easier to get some testing & early adoption if there's a tagged release.

**Comment by workmanw** [comment]
As mentioned in the PR, we'll try to get a new release out today.

**Comment by XaserAcheron** [comment]
Oops, my bad -- I missed the latest comments in the PR thread.

**Comment by workmanw** [comment]
Released
