### ISSUE TITLE
5.0.0-beta.0: Computed property perpetually recalculating

### ISSUE THREAD

**Issue by backspace** [lytics/ember-data-model-fragments#369]
Hey, I’m trying out the new beta as I attempt to [update to Ember 3.16](https://github.com/hashicorp/nomad/pull/8094). I had some trouble with a test that was hanging and narrowed it down to a computed property within a model fragment. I’m out of my depth in debugging at this point and I’m definitely not sure it’s a problem with the beta but that‘s my suspicion at least…

I narrowed down the hanging test to [this template conditional](https://github.com/hashicorp/nomad/pull/8094/files#diff-e9384f4a5325ab05993f45ba8c7b4ae8L2), among others. `allocation.unhealthyDrivers` is a [computed property](https://github.com/hashicorp/nomad/blob/f-ui/ember-3.16-lts/ui/app/models/allocation.js#L90) that has two dependent keys; I added some logging and found that the one that was perpetually recalculating was `taskGroup.drivers.[]`, which is [defined](https://github.com/hashicorp/nomad/blob/f-ui/ember-3.16-lts/ui/app/models/task-group.js#L21-L23) in a fragment.

I wondered whether changing the definition to use `mapBy` and `uniq` might help, but it didn’t change anything.

I made an observer on `taskGroup.drivers.[]` and put a debugger so I could inspect the stack and saw some model fragments calls:

<img width="587" alt="image" src="https://user-images.githubusercontent.com/43280/83905043-947c6e80-a726-11ea-8e78-a98f831f55d6.png">

This might be a red herring though! I feel stuck but let me know if you would like more information or we could pair at some point or the like. Thanks for all the work on this library!

**Comment by patocallaghan** [comment]
@backspace is it possible to create a simple test reproduction either in a separate repo or submit it as a PR here?

**Comment by backspace** [comment]
I can try! Hopefully some time next week 🤞💞

**Comment by backspace** [comment]
well I started a new application and tried to mirror the model structure that is implicated in this infinite loop but I was unable to reproduce the problem. I’m at the limit of my debugging skills and can’t say whether the presence of this library in the stack traces is an actual cause or just a side effect. So I’ll close this issue 😞
